name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的tag时触发，如 v1.0.0
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.27.0'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Create keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos/
          mkdir Payload
          cp -r Runner.app Payload/
          zip -qq -r -9 app-release.ipa Payload

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app-release.ipa

  upload:
    runs-on: ubuntu-latest
    needs: [ build-android, build-ios ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          merge-multiple: true

      - name: List files
        run: tree dist

      - name: Prepare scripts
        run: |
          mkdir -p .github/scripts
          chmod +x .github/scripts/process_commits.sh

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Generate commit messages
        id: commits
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD --pretty=format:"%s%n%b" | .github/scripts/process_commits.sh)
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: false
          body: |
            🚧 This is a pre-release version
            
            ### Build Information
            - Version: ${{ github.ref_name }}
            - Previous Version: ${{ steps.previoustag.outputs.tag }}
            - Built with Flutter ${{ env.FLUTTER_VERSION }}
            
            ### Changes since last release
            ${{ steps.commits.outputs.commits }}
            
            ⚠️ This version may contain bugs and is not recommended for production use.
            
            ### Download
            - APK: Direct installation file for Android
            - AAB: Android App Bundle for Play Store submission
          files: |
            dist/app-release.apk
            dist/app-release.aab
            dist/app-release.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts if not release
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: actions/upload-artifact@v4
        with:
          name: everything
          path: dist/
